- block:
    - name: Executing script windows
      script: ../scripts/windows-copy-install.ps1
      become: yes
      register: script_output
      environment:
         nas_path: '{{ nas_path_win }}'
         mount_username: '{{ mount_username }}'
         mount_password: '{{ mount_password }}'
  always:
    - name: Script output
      debug:
        msg: "{{ script_output }}"
